#!/usr/bin/env python3
"""
Generates a new entity's model + router, following the same pattern
as `item.py`/`items.py` — the one every entity in this template
follows. Doesn't touch main.py or alembic/env.py automatically
(too risky to edit those blind); it prints the exact lines to add
by hand instead.

Usage:
    python3 scaffold_entity.py Patient
    python3 scaffold_entity.py WorkOrder
"""

import sys
from pathlib import Path

MODEL_TEMPLATE = '''"""
{name} — generated by scaffold_entity.py. Adjust fields to match
the client's actual entity; this starting shape follows the same
pattern as every other model in the template.
"""

from datetime import datetime

from sqlmodel import Field, SQLModel


class {name}Base(SQLModel):
    name: str = Field(index=True, max_length=200)
    description: str | None = None
    is_active: bool = Field(default=True, index=True)
    account_id: int | None = Field(default=None, foreign_key="account.id", index=True)


class {name}({name}Base, table=True):
    __tablename__ = "{table_name}"

    id: int | None = Field(default=None, primary_key=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class {name}Create({name}Base):
    pass


class {name}Read({name}Base):
    id: int
    created_at: datetime
    updated_at: datetime


class {name}Update(SQLModel):
    name: str | None = None
    description: str | None = None
    is_active: bool | None = None
    account_id: int | None = None
'''

ROUTER_TEMPLATE = '''"""
{name} CRUD router — generated by scaffold_entity.py, follows the
same auth-protected pattern as every other router in the template.
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from app.core.deps import get_current_account
from app.db.session import get_session
from app.models.{module_name} import {name}, {name}Create, {name}Read, {name}Update

router = APIRouter(
    prefix="/{route_prefix}", tags=["{route_prefix}"], dependencies=[Depends(get_current_account)]
)


@router.get("/", response_model=list[{name}Read])
async def list_{plural_lower}(session: AsyncSession = Depends(get_session)):
    result = await session.exec(select({name}))
    return result.all()


@router.post("/", response_model={name}Read, status_code=201)
async def create_{singular_lower}(
    item_in: {name}Create, session: AsyncSession = Depends(get_session)
):
    item = {name}.model_validate(item_in)
    session.add(item)
    await session.commit()
    await session.refresh(item)
    return item


@router.get("/{{item_id}}", response_model={name}Read)
async def get_{singular_lower}(item_id: int, session: AsyncSession = Depends(get_session)):
    item = await session.get({name}, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="{name} not found")
    return item


@router.patch("/{{item_id}}", response_model={name}Read)
async def update_{singular_lower}(
    item_id: int, item_in: {name}Update, session: AsyncSession = Depends(get_session)
):
    item = await session.get({name}, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="{name} not found")
    for field, value in item_in.model_dump(exclude_unset=True).items():
        setattr(item, field, value)
    session.add(item)
    await session.commit()
    await session.refresh(item)
    return item


@router.delete("/{{item_id}}", status_code=204)
async def delete_{singular_lower}(item_id: int, session: AsyncSession = Depends(get_session)):
    item = await session.get({name}, item_id)
    if not item:
        raise HTTPException(status_code=404, detail="{name} not found")
    await session.delete(item)
    await session.commit()
'''


def to_snake_case(name: str) -> str:
    result = []
    for i, char in enumerate(name):
        if char.isupper() and i > 0:
            result.append("_")
        result.append(char.lower())
    return "".join(result)


def main():
    if len(sys.argv) != 2:
        print("Usage: python3 scaffold_entity.py EntityName")
        print("Example: python3 scaffold_entity.py WorkOrder")
        sys.exit(1)

    name = sys.argv[1]
    if not name[0].isupper():
        print("Entity name should be PascalCase, e.g. WorkOrder, Patient, Invoice")
        sys.exit(1)

    module_name = to_snake_case(name)
    table_name = module_name
    route_prefix = module_name + "s"  # naive pluralization — fix by hand if it's e.g. "Company"
    plural_lower = route_prefix
    singular_lower = module_name

    backend_dir = Path(__file__).resolve().parent
    model_path = backend_dir / "app" / "models" / f"{module_name}.py"
    router_path = backend_dir / "app" / "api" / f"{route_prefix}.py"

    if model_path.exists() or router_path.exists():
        print(f"Refusing to overwrite — {model_path.name} or {router_path.name} already exists.")
        sys.exit(1)

    model_path.write_text(MODEL_TEMPLATE.format(name=name, table_name=table_name))
    router_path.write_text(
        ROUTER_TEMPLATE.format(
            name=name,
            module_name=module_name,
            route_prefix=route_prefix,
            plural_lower=plural_lower,
            singular_lower=singular_lower,
        )
    )

    print(f"Created:")
    print(f"  {model_path.relative_to(backend_dir)}")
    print(f"  {router_path.relative_to(backend_dir)}")
    print()
    print("Manual steps still required:")
    print(f"  1. In app/main.py:")
    print(f"     from app.api import {route_prefix}")
    print(f"     app.include_router({route_prefix}.router)")
    print(f"  2. In alembic/env.py, add:")
    print(f"     from app.models.{module_name} import {name}  # noqa: F401")
    print(f"  3. Adjust the model's fields to match the client's real entity")
    print(f"     — the generated version is a starting shape, not final.")
    print(f"  4. Generate and apply the migration:")
    print(f'     alembic revision --autogenerate -m "add {module_name}"')
    print(f"     alembic upgrade head")


if __name__ == "__main__":
    main()
