"""initial unified account schema

Revision ID: 150bc11cf1cb
Revises: 
Create Date: 2026-08-12 19:51:31.973935

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '150bc11cf1cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
    sa.Column('tier', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_email'), 'account', ['email'], unique=True)
    op.create_index(op.f('ix_account_is_active'), 'account', ['is_active'], unique=False)
    op.create_index(op.f('ix_account_tier'), 'account', ['tier'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('old_values', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_values', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_changed_by'), 'audit_log', ['changed_by'], unique=False)
    op.create_index(op.f('ix_audit_log_created_at'), 'audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_log_record_id'), 'audit_log', ['record_id'], unique=False)
    op.create_index(op.f('ix_audit_log_table_name'), 'audit_log', ['table_name'], unique=False)
    op.create_table('deleted_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('tier_at_deletion', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('deleted_by', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('restored_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deleted_account_account_id'), 'deleted_account', ['account_id'], unique=False)
    op.create_index(op.f('ix_deleted_account_deleted_at'), 'deleted_account', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_deleted_account_deleted_by'), 'deleted_account', ['deleted_by'], unique=False)
    op.create_index(op.f('ix_deleted_account_tier_at_deletion'), 'deleted_account', ['tier_at_deletion'], unique=False)
    op.create_table('item',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_account_id'), 'item', ['account_id'], unique=False)
    op.create_index(op.f('ix_item_is_active'), 'item', ['is_active'], unique=False)
    op.create_index(op.f('ix_item_name'), 'item', ['name'], unique=False)
    op.create_table('transaction',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('created', 'updated', 'completed', 'cancelled', name='transactiontype'), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_account_id'), 'transaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_transaction_created_at'), 'transaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_created_by'), 'transaction', ['created_by'], unique=False)
    op.create_index(op.f('ix_transaction_item_id'), 'transaction', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_item_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_created_by'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_created_at'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_account_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_item_name'), table_name='item')
    op.drop_index(op.f('ix_item_is_active'), table_name='item')
    op.drop_index(op.f('ix_item_account_id'), table_name='item')
    op.drop_table('item')
    op.drop_index(op.f('ix_deleted_account_tier_at_deletion'), table_name='deleted_account')
    op.drop_index(op.f('ix_deleted_account_deleted_by'), table_name='deleted_account')
    op.drop_index(op.f('ix_deleted_account_deleted_at'), table_name='deleted_account')
    op.drop_index(op.f('ix_deleted_account_account_id'), table_name='deleted_account')
    op.drop_table('deleted_account')
    op.drop_index(op.f('ix_audit_log_table_name'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_record_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_created_at'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_changed_by'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_account_tier'), table_name='account')
    op.drop_index(op.f('ix_account_is_active'), table_name='account')
    op.drop_index(op.f('ix_account_email'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
