"""add low_stock_threshold field

Revision ID: 5d07c0348d72
Revises: 95070233075c
Create Date: 2026-08-27 18:34:37.501915

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '5d07c0348d72'
down_revision = '95070233075c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('low_stock_threshold', sa.Integer(), nullable=True))
    op.create_check_constraint('ck_item_low_stock_threshold_non_negative', 'item', 'low_stock_threshold IS NULL OR low_stock_threshold >= 0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_item_low_stock_threshold_non_negative', 'item', type_='check')
    op.drop_column('item', 'low_stock_threshold')
    # ### end Alembic commands ###
