"""add image_url field to item

Revision ID: 7e6b1357cd37
Revises: 61c8d0719696
Create Date: 2026-09-01 20:58:55.668455

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '7e6b1357cd37'
down_revision = '61c8d0719696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'image_url')
    # ### end Alembic commands ###
