"""add payment_reference field for future payment provider integration

Revision ID: 95070233075c
Revises: ff1aa3d5c80d
Create Date: 2026-08-27 17:25:32.376821

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '95070233075c'
down_revision = 'ff1aa3d5c80d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('payment_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))
    op.create_index(op.f('ix_transaction_payment_reference'), 'transaction', ['payment_reference'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_payment_reference'), table_name='transaction')
    op.drop_column('transaction', 'payment_reference')
    # ### end Alembic commands ###
