"""audit log writers, password reset, refund linkage

Revision ID: 9e8a61a99ede
Revises: edfb68e24c74
Create Date: 2026-08-26 18:56:43.369367

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '9e8a61a99ede'
down_revision = 'edfb68e24c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('reset_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('account', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_account_reset_token_hash'), 'account', ['reset_token_hash'], unique=False)
    op.add_column('transaction', sa.Column('related_transaction_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transaction_related_transaction_id'), 'transaction', ['related_transaction_id'], unique=False)
    op.create_foreign_key(None, 'transaction', 'transaction', ['related_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_index(op.f('ix_transaction_related_transaction_id'), table_name='transaction')
    op.drop_column('transaction', 'related_transaction_id')
    op.drop_index(op.f('ix_account_reset_token_hash'), table_name='account')
    op.drop_column('account', 'reset_token_expires')
    op.drop_column('account', 'reset_token_hash')
    # ### end Alembic commands ###
