"""add item commerce fields, transaction deposits, appointments, appointment-transaction link

Revision ID: a956863caba3
Revises: 150bc11cf1cb
Create Date: 2026-08-18 16:30:29.818772

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'a956863caba3'
down_revision = '150bc11cf1cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
