"""add check constraints for price and quantity

Revision ID: d37b1048ac2d
Revises: 9e8a61a99ede
Create Date: 2026-08-26 19:25:43.812601

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'd37b1048ac2d'
down_revision = '9e8a61a99ede'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_item_price_non_negative', 'item', 'price IS NULL OR price >= 0')
    op.create_check_constraint('ck_item_stock_quantity_non_negative', 'item', 'stock_quantity IS NULL OR stock_quantity >= 0')
    op.create_check_constraint('ck_transaction_line_line_total_non_negative', 'transaction_line', 'line_total >= 0')
    op.create_check_constraint('ck_transaction_line_quantity_positive', 'transaction_line', 'quantity >= 1')
    op.create_check_constraint('ck_transaction_line_unit_price_non_negative', 'transaction_line', 'unit_price >= 0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_transaction_line_unit_price_non_negative', 'transaction_line', type_='check')
    op.drop_constraint('ck_transaction_line_quantity_positive', 'transaction_line', type_='check')
    op.drop_constraint('ck_transaction_line_line_total_non_negative', 'transaction_line', type_='check')
    op.drop_constraint('ck_item_stock_quantity_non_negative', 'item', type_='check')
    op.drop_constraint('ck_item_price_non_negative', 'item', type_='check')
    # ### end Alembic commands ###
