"""initial schema

Revision ID: edfb68e24c74
Revises: a956863caba3
Create Date: 2026-08-26 18:32:55.506164

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = 'edfb68e24c74'
down_revision = 'a956863caba3'
branch_labels = None
depends_on = None

payment_method_enum = sa.Enum('cash', 'card', 'bank_transfer', 'other', name='paymentmethod')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    payment_method_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('attachment',
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('file_url', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_created_at'), 'attachment', ['created_at'], unique=False)
    op.create_index(op.f('ix_attachment_entity_id'), 'attachment', ['entity_id'], unique=False)
    op.create_index(op.f('ix_attachment_entity_type'), 'attachment', ['entity_type'], unique=False)
    op.create_index(op.f('ix_attachment_uploaded_by'), 'attachment', ['uploaded_by'], unique=False)
    op.create_table('notification',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_account_id'), 'notification', ['account_id'], unique=False)
    op.create_index(op.f('ix_notification_created_at'), 'notification', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_created_by'), 'notification', ['created_by'], unique=False)
    op.create_table('transaction_line',
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_total', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_line_item_id'), 'transaction_line', ['item_id'], unique=False)
    op.create_index(op.f('ix_transaction_line_transaction_id'), 'transaction_line', ['transaction_id'], unique=False)
    op.add_column('item', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('item', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('item', sa.Column('sku', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('item', sa.Column('stock_quantity', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_item_category'), 'item', ['category'], unique=False)
    op.create_index(op.f('ix_item_sku'), 'item', ['sku'], unique=True)
    op.add_column('transaction', sa.Column('guest_label', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('transaction', sa.Column('payment_method', payment_method_enum, nullable=True))
    op.add_column('transaction', sa.Column('subtotal', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('tax_amount', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('total', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('deposit_amount', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('balance_due', sa.Float(), nullable=True))
    op.alter_column('transaction', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_transaction_item_id'), table_name='transaction')
    op.drop_constraint(op.f('transaction_item_id_fkey'), 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('transaction_item_id_fkey'), 'transaction', 'item', ['item_id'], ['id'])
    op.create_index(op.f('ix_transaction_item_id'), 'transaction', ['item_id'], unique=False)
    op.alter_column('transaction', 'account_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('transaction', 'balance_due')
    op.drop_column('transaction', 'deposit_amount')
    op.drop_column('transaction', 'total')
    op.drop_column('transaction', 'tax_amount')
    op.drop_column('transaction', 'subtotal')
    op.drop_column('transaction', 'payment_method')
    op.drop_column('transaction', 'guest_label')
    op.drop_index(op.f('ix_item_sku'), table_name='item')
    op.drop_index(op.f('ix_item_category'), table_name='item')
    op.drop_column('item', 'duration_minutes')
    op.drop_column('item', 'stock_quantity')
    op.drop_column('item', 'sku')
    op.drop_column('item', 'price')
    op.drop_column('item', 'category')
    op.drop_index(op.f('ix_transaction_line_transaction_id'), table_name='transaction_line')
    op.drop_index(op.f('ix_transaction_line_item_id'), table_name='transaction_line')
    op.drop_table('transaction_line')
    op.drop_index(op.f('ix_notification_created_by'), table_name='notification')
    op.drop_index(op.f('ix_notification_created_at'), table_name='notification')
    op.drop_index(op.f('ix_notification_account_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_attachment_uploaded_by'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_entity_type'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_entity_id'), table_name='attachment')
    op.drop_index(op.f('ix_attachment_created_at'), table_name='attachment')
    op.drop_table('attachment')

    payment_method_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
